/* --- 100 Quotes Generator --- */
const quotes = [
    "Giữa chốn an yên, tâm hồn bạn chính là giai điệu thuần khiết nhất của đại ngàn.",
    "Nơi nào có tĩnh lặng, nơi đó lòng người bình an như mặt hồ sương sớm.",
    "Hãy để làn gió thung lũng cuốn đi những muộn phiền, chỉ giữ lại sự trong trẻo của khoảnh khắc này.",
    "Mỗi luồng sáng xuyên qua mây mù là một lời nhắc nhở: Bình minh luôn chờ đợi phía sau ngọn núi.",
    "Âm vang của vĩnh cửu không nằm ở đâu xa, mà đọng lại trong từng hơi thở sâu giữa thiên nhiên.",
    "Khi tim ta dịu lại, cả thế giới xung quanh cũng ngừng xôn xao.",
    "Mỗi chiếc lá rơi đều mang theo một thông điệp từ sự buông bỏ nhẹ nhàng.",
    "Lắng nghe tiếng suối chảy để biết rằng cuộc đời luôn tiếp diễn mềm mại.",
    "Thung lũng che chở những tâm hồn mệt mỏi bằng sự tĩnh lặng nguyên sơ.",
    "Hãy bước chậm lại để cảm nhận hương vị ngọt ngào của ngọn gió ban mai.",
    "Tĩnh lặng không phải là khoảng trống, tĩnh lặng là câu trả lời.",
    "Sương mờ có thể che lối, nhưng ánh sáng trong tim sẽ luôn dẫn đường.",
    "Cây đại thụ từng là một hạt mầm kiên nhẫn chịu đựng bão giông.",
    "Chỉ khi học được cách buông tay, bạn mới đón nhận được những điều tuyệt vời mới.",
    "Nắng ấm luôn biết cách tìm đến những mầm cây kiên cường nhất.",
    "Hoàng hôn là bằng chứng cho thấy sự kết thúc cũng có thể rực rỡ đến vương vấn.",
    "Mỗi giọt sương mai đều chứa đựng ước mơ của bầu trời đêm.",
    "Hãy dịu dàng với chính mình như cách làn sương ôm lấy ngọn đồi.",
    "Sức mạnh của đá nằm ở sự kiên trì, sức mạnh của dòng nước nằm ở sự mềm mại.",
    "Trở về với thiên nhiên là chuyến trở về bình yên nhất của tâm hồn.",
    "Núi cao không tranh chấp với mây, tâm rộng không vương mang phiền muộn.",
    "Âm nhạc của đất trời không cần lời, chỉ cần một trái tim biết lắng nghe.",
    "Bình yên là khi bạn mỉm cười với hiện tại mà không lo lắng về tương lai.",
    "Hãy là ngọn cỏ mềm biết uốn mình trước bão dông chứ đừng gãy gập.",
    "Mỗi ngày mới là một cơ hội để bắt đầu lại bằng sự trong lành.",
    "Dưới bầu trời sao vĩnh cửu, nỗi lo của chúng ta chỉ là những hạt bụi nhỏ.",
    "Tình yêu thương giống như ánh nắng, sưởi ấm mọi ngóc ngách tối tăm.",
    "Đừng vội vã, hoa nở đúng thời điểm mới tỏa ngát hương thơm nhất.",
    "Gió nhẹ xoay chuyển lòng người, tĩnh tâm xoay chuyển vạn vật.",
    "Hãy tìm kiếm sự an yên ngay bên trong, nơi không bão tố nào chạm tới.",
    "Cảm nhận từng nốt nhạc của cuộc sống như cách suối reo qua khe đá.",
    "Con đường dài nhất luôn bắt đầu bằng một bước chân kiên định.",
    "Mỗi cánh hoa oải hương đều lưu giữ mùi hương của sự thư thái.",
    "Hãy học cách tha thứ để trái tim bạn nhẹ nhàng như mây bay.",
    "Mùa thu trút lá không phải để héo mòn, mà để chuẩn bị cho mầm xanh mới.",
    "Niềm vui đơn sơ đôi khi chỉ là một tách trà nóng giữa không gian thanh bình.",
    "Trời càng tối, những vì sao lại càng tỏa sáng rực rỡ.",
    "Hãy sống trọn vẹn từng giây phút như thể đó là giai điệu đẹp nhất.",
    "Bình an nội tâm là món quà quý giá nhất bạn có thể tự trao cho mình.",
    "Hãy đón nhận cơn mưa vì nó mang lại sự sống cho cánh đồng khô hạn.",
    "Mọi giông bão rồi cũng sẽ qua, nhường chỗ cho bầu trời xanh trong.",
    "Bước chân thư thái sẽ đưa bạn đến những nơi tuyệt đẹp.",
    "Dù đi xa đến đâu, sự bình yên vẫn luôn nằm ở điểm dừng trong tâm.",
    "Hãy lắng nghe tiếng thì thầm của trái tim trước khi lắng nghe dư luận.",
    "Kính trọng quá khứ, yêu thương hiện tại và đón nhận tương lai.",
    "Tâm hồn trong trẻo nhìn đâu cũng thấy cảnh sắc hữu tình.",
    "Hãy như ngọn núi, đứng vững vàng giữa muôn vàn biến đổi.",
    "Tình bạn chân thành giống như dòng suối mát lành giữa sa mạc.",
    "Bên cạnh sự kiên trì, sự nghỉ ngơi cũng là một nghệ thuật sống.",
    "Nụ cười mỉm chân thật có thể làm dịu đi muôn vàn âu lo.",
    "Hãy thả trôi những muộn phiền theo dòng nước về chốn xa xôi.",
    "Tĩnh lặng giữa thung lũng giúp ta thấu hiểu chính mình.",
    "Không có con đường nào dẫn đến bình yên, bình yên chính là con đường.",
    "Đất mẹ luôn bao dung và nâng đỡ từng bước chân nhỏ bé.",
    "Mỗi hơi thở vào là năng lượng tươi mới, mỗi hơi thở ra là sự thả lỏng.",
    "Cuộc sống là một bản hòa tấu, hãy chọn chơi những nốt nhạc yêu thương.",
    "Ước mơ giống như những vì sao, có thể xa xôi nhưng luôn chỉ hướng.",
    "Biết ơn những gì đang có là chìa khóa mở ra hạnh phúc vĩnh cửu.",
    "Thời gian trôi qua không trở lại, hãy trân trọng từng khoảnh khắc xanh.",
    "Hương thơm của lòng tốt luôn lan tỏa xa hơn muôn ngàn loài hoa.",
    "Hãy kiên nhẫn với chính mình, mọi điều tốt đẹp đều cần thời gian.",
    "Dãy núi mù sương gợi nhớ về những điều bí ẩn đầy mê hoặc.",
    "Mỗi bình minh là một trang sách trắng đợi bạn viết lên những điều tươi đẹp.",
    "Sống như một bông hoa dại, tự do tỏa sáng giữa đất trời.",
    "Không gian tĩnh lặng là nơi nuôi dưỡng những ý tưởng tuyệt vời nhất.",
    "Gửi trao đi tình yêu, bạn sẽ nhận lại sự an lành.",
    "Hãy mỉm cười khi đón nhận những tia nắng đầu tiên trong ngày.",
    "Khi lòng bạn lắng xuống, mọi vướng bận tự khắc tan biến.",
    "Một trái tim biết ơn luôn tìm thấy lý do để hạnh phúc.",
    "Tiếng chim hót ríu rít là khúc ca hy vọng của buổi sớm mai.",
    "Hãy buông bỏ những điều không thuộc về mình để sống nhẹ nhàng hơn.",
    "Khoảng trầm trong âm nhạc tạo nên độ sâu, khoảng trầm cuộc đời tạo nên độ chín.",
    "Nhìn sâu vào thiên nhiên, bạn sẽ hiểu mọi thứ rõ ràng hơn.",
    "Mỗi khoảnh khắc hiện tại là một món quà kỳ diệu.",
    "Sức mạnh thật sự không nằm ở cơ bắp, mà nằm ở sự kiên định của tinh thần.",
    "Sống chan hòa như nước, sẵn sàng ôm trọn mọi hình dáng.",
    "Thung lũng vĩnh cửu luôn mở rộng vòng tay đón chào người lữ khách mệt mỏi.",
    "Nụ cười là ngôn ngữ chung của sự ấm áp và bình yên.",
    "Hãy giữ cho tâm trí thanh thản như mặt nước hồ thu.",
    "Mọi trải nghiệm đều là bài học đắt giá trên hành trình trưởng thành.",
    "Chỉ cần lòng bình an, ở đâu cũng là quê hương.",
    "Nắng ấm sưởi ấm mầm xanh, sự dịu dàng sưởi ấm lòng người.",
    "Hãy sống một cuộc đời chân thật với những giá trị cốt lõi.",
    "Sự giản dị mang lại vẻ đẹp thanh cao vượt thời gian.",
    "Mỗi bông hoa nở đều mang một niềm vui nhỏ cho trái đất.",
    "Đừng sợ hãi bóng tối, vì đó là lúc bạn nhìn rõ những vì sao nhất.",
    "Dòng sông chảy không bao giờ ngoảnh lại, hãy tiến về phía trước.",
    "Sự thấu hiểu là nhịp cầu kết nối những tâm hồn xa lạ.",
    "Hãy như cây tùng, đứng thẳng và ngẩng cao đầu trước gió tuyết.",
    "Mỗi ngọn gió thoảng qua đều mang theo những phép màu dịu nhẹ.",
    "Thư thái tâm hồn là liều thuốc chữa lành tự nhiên nhất.",
    "Hãy tìm niềm vui trong những điều bình dị thường ngày.",
    "Khi bạn hòa mình với thiên nhiên, bạn không bao giờ cô đơn.",
    "Sự kiên nhẫn sẽ đơm hoa kết trái ngọt ngào.",
    "Tình yêu thiên nhiên phản chiếu sự trong sáng của tâm hồn.",
    "Mỗi ngày trôi qua là một nhịp điệu nhẹ nhàng của vũ trụ.",
    "Nơi nào có chân thành, nơi đó có sự ấm áp chân thật.",
    "Hãy để tâm hồn bạn tự do bay bổng như những đám mây trắng.",
    "Sự tĩnh lặng giữa thung lũng là chốn nương tựa tuyệt vời.",
    "Vĩnh Cửu không phải là mãi mãi, mà là trọn vẹn trong từng giây phút."
];

function generateNewQuote() {
    const quoteElem = document.getElementById('quoteText');
    quoteElem.style.opacity = '0';
    setTimeout(() => {
        const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
        quoteElem.innerText = `"${randomQuote}"`;
        quoteElem.style.opacity = '1';
    }, 300);
}